version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - webboxesdeveloper
    target-branch: "staging"
    versioning-strategy: increase
