export const actionTypes = {
  LOGIN: 'LOGIN',
  SET_REST_BAR_CLASS: "SET_REST_BAR_CLASS",
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGGED_IN: 'LOGGED_IN',
  SET_BASE_URI: 'SET_BASE_URI',
  SET_MOBILE_TOKEN: 'SET_MOBILE_TOKEN',

  LOADING: 'LOADING',
  SUCCESS_NOTIFICATION: 'SUCCESS_NOTIFICATION',
  ERROR_NOTIFICATION: 'ERROR_NOTIFICATION',
  SET_VISIBLE_SUCCESS_MODAL: 'SET_VISIBLE_SUCCESS_MODAL',

  SET_MEDICAL_QUESTIONS: 'SET_MEDICAL_QUESTIONS',

  QUERY_ALL_ORGANIZATIONS: 'QUERY_ALL_ORGANIZATIONS',
  ALL_ORGANIZATIONS: 'ALL_ORGANIZATIONS',
  QUERY_ALL_TEAMS: 'QUERY_ALL_TEAMS',
  ALL_TEAMS: 'ALL_TEAMS',
  QUERY_TEAM_MEMBERS: 'QUERY_TEAM_MEMBERS',
  TEAM_MEMBERS: 'TEAM_MEMBERS',
  REMOVE_TEAM_MEMBER: 'REMOVE_TEAM_MEMBER',
  DELETE_USER: 'DELETE_USER',
};